# Generated by Django 4.0 on 2022-08-12 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_author_country_topic_rename_avatar_user_picture_tale_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='topic',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
