# Generated by Django 4.0 on 2022-08-18 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favourite_tale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.tale'),
        ),
    ]
